// Generated from exact, non-interpolated production Semantics identifiers.
//
// Keep this registry exact-value only. Dynamic row/object identifiers, keypad
// digits, and user/input-derived identifiers must never be added. The source
// inventory contract in secret_redactor_test.dart fails when a new static
// action identifier is not deliberately classified.
const Set<String> kAuditedStaticInteractionIdentifiers = <String>{
  '_register_hero',
  '_register_hero_logo',
  '_request_empty_state_new_order_button',
  '_super_login_link',
  '_super_login_submit_cta',
  'account_status_signout_cta',
  'account_status_support_cta',
  'availability_inactivity_extend_cta',
  'availability_switch',
  'become_jeeber_card_cta',
  'biometric_prompt_authenticate_cta',
  'biometric_unlock_authenticate_cta',
  'cancel_request_confirm_cta',
  'cancel_request_error',
  'cancel_request_free_note',
  'cancel_request_keep_cta',
  'cancel_request_sheet',
  'cancellation_back',
  'cancellation_error_note',
  'cancellation_root',
  'cancellation_sheet_done_cta',
  'cancellation_submit_cta',
  'cancellation_too_late',
  'charge_info_back',
  'charge_info_back_cta',
  'charge_info_identity_step',
  'charge_info_pay_cash_step',
  'charge_info_store_step',
  'client_home_mic_cta',
  'client_home_recording_waveform',
  'client_home_retry_cta',
  'client_home_voice_blocked_retry',
  'client_home_voice_retry_tier',
  'client_home_voice_retry_upload',
  'client_home_voice_tier_type_cta',
  'client_home_voice_type_cta',
  'client_unreachable_back',
  'client_unreachable_call_again_cta',
  'client_unreachable_flag_cta',
  'compose_description_mic',
  'compose_tier_retry',
  'compose_tier_row',
  'compose_tier_sheet_retry',
  'confirm_delivery_action_sheet',
  'confirm_delivery_confirm_button',
  'confirm_delivery_drag_handle',
  'confirm_delivery_illustration',
  'confirm_delivery_subtitle',
  'confirm_delivery_title',
  'customer_profile_contact_row',
  'customer_profile_language_row',
  'customer_profile_logout_row',
  'customer_profile_notifications_row',
  'customer_profile_rate_app_row',
  'customer_profile_register_delivery_row',
  'customer_wallet_stub',
  'customer_wallet_stub_back',
  'customer_wallet_stub_done',
  'deep_link_kyc_status_root',
  'delivery-rating-summary-done',
  'delivery_register_prompt',
  'delivery_register_prompt_back',
  'delivery_register_prompt_cta',
  'delivery_register_prompt_top_back',
  'delivery_status_back',
  'delivery_status_cancel_cta',
  'delivery_status_contact_cta',
  'devtool.scenarioUsers.approveKyc',
  'devtool.scenarioUsers.create',
  'devtool.scenarioUsers.makeOnlineReady',
  'devtool.scenarioUsers.scenario',
  'devtool.session_logs.clear',
  'devtool.session_logs.export',
  'devtool.session_logs.recording',
  'devtool.walletFunding.cleanup',
  'devtool.walletFunding.home',
  'devtool.walletFunding.lastCreated',
  'devtool.walletFunding.submit',
  'dispute_auto_attach_note',
  'dispute_back',
  'dispute_error',
  'dispute_photos',
  'dispute_photos_add_cta',
  'dispute_reason',
  'dispute_root',
  'dispute_status_back',
  'dispute_status_error',
  'dispute_status_evidence_empty',
  'dispute_status_evidence_partial',
  'dispute_status_evidence_summary',
  'dispute_status_history',
  'dispute_status_loading',
  'dispute_status_outcome',
  'dispute_status_retry_cta',
  'dispute_status_root',
  'dispute_status_state',
  'dispute_status_stepper',
  'dispute_status_support',
  'dispute_submit_cta',
  'dispute_submitting',
  'dispute_support_link',
  'dispute_upload_progress',
  'dispute_voice',
  'dm_onboarding_back',
  'dm_onboarding_photo_upload_area',
  'earnings_activity_link',
  'earnings_export_cta',
  'earnings_wallet_link',
  'feed_make_offer_cta',
  'feedback_ratee_avatar',
  'feedback_star_rating',
  'feedback_submit_loading',
  'funding_back',
  'funding_continue_cta',
  'funding_starter_credit_amount',
  'funding_topup_cta',
  'funding_wallet_retry',
  'gate_back_cta',
  'gate_register_link',
  'gate_start_kyc_cta',
  'gate_topup_note',
  'goods_cost_back',
  'goods_cost_submit_cta',
  'in_progress_create_cta',
  'in_progress_retry_cta',
  'insufficient_keep_editing_cta',
  'insufficient_topup_cta',
  'jeeber-request-detail-decline',
  'jeeber_feed_empty_refresh_cta',
  'jeeber_feed_filter_open',
  'jeeber_feed_filter_pill_query',
  'jeeber_feed_filter_pill_tier',
  'jeeber_feed_filter_sheet',
  'jeeber_feed_pending_tab',
  'jeeber_feed_replies_tab',
  'jeeber_feed_requests_tab',
  'jeeber_home_accept_orders_switch',
  'jeeber_home_load_error_retry_cta',
  'jeeber_request_detail_back',
  'jeeber_request_unavailable_back',
  'jeeber_unregistered_empty_state',
  'jeeber_unregistered_register_button',
  'jeeber_unregistered_root',
  'kyc_id_back_upload',
  'kyc_id_front_upload',
  'kyc_rejected_appeal_cta',
  'kyc_rejected_back',
  'kyc_rejected_back_cta',
  'kyc_selfie_upload',
  'kyc_status_back',
  'kyc_status_check_again_cta',
  'kyc_status_feed_cta',
  'kyc_status_resubmit_cta',
  'kyc_status_resubmit_steps',
  'kyc_status_topup_allowed_note',
  'kyc_status_topup_cta',
  'kyc_status_wallet_cta',
  'kyc_submit_cta',
  'kyc_tos_accept',
  'kyc_tos_read_cta',
  'kyc_wizard_back',
  'kyc_wizard_retry_cta',
  'language_arabic_option',
  'language_back',
  'language_english_option',
  'logout_delete_account_root',
  'logout_delete_cancel_cta',
  'logout_delete_confirm_sheet',
  'delete_confirm_cta',
  'logout_confirm_cta',
  'logout_delete_sheet',
  'mark_delivered_advance_cta',
  'mark_delivered_back',
  'mark_delivered_cta',
  'mark_delivered_goods_cost_cta',
  'mark_delivered_open_maps_cta',
  'mark_delivered_proof_photo',
  'masked_call_cta',
  'mutual_rating_ratee_avatar',
  'notif_perm_dismiss',
  'notif_perm_enable',
  'notif_prefs_back',
  'notif_prefs_marketing_toggle',
  'notif_prefs_offers_toggle',
  'notif_prefs_order_status_toggle',
  'notif_prefs_retry_cta',
  'notif_prefs_wallet_toggle',
  'notifications_back',
  'notifications_retry_cta',
  'obs_overlay_bubble',
  'offer_accept_cancel_cta',
  'offer_accept_confirm_cta',
  'offer_accept_error',
  'offer_accept_jeeber_name',
  'offer_accept_other_offers_note',
  'offer_accept_price_label',
  'offer_accept_sheet',
  'offer_accepted_banner',
  'offer_accepted_banner_text',
  'offer_accepted_dismiss_cta',
  'offer_accepted_track_cta',
  'offer_composer_close_cta',
  'offer_composer_send_cta',
  'offer_composer_wallet_strip',
  'offer_composer_wallet_topup_cta',
  'offer_kyc_gate_back',
  'offer_review_back',
  'offer_review_cancel_cta',
  'offer_review_error_dismiss_cta',
  'offer_review_retry_cta',
  'offer_review_waiting_window_chip',
  'offer_status_filter_empty',
  'offline_banner_dismiss_cta',
  'onboarding_language_toggle',
  'onboarding_next_button',
  'order-detail-cancel',
  'order_detail_back',
  'order_history_filter_chip',
  'order_history_retry_cta',
  'order_history_sheet_apply_cta',
  'order_history_sheet_clear_cta',
  'order_summary_back',
  'order_summary_retry_cta',
  'order_summary_track',
  'orders_create_request_button',
  'orders_filter_open',
  'orders_filter_pill_bucket',
  'orders_filter_pill_status',
  'orders_home_replies_tab',
  'pending_offers_back',
  'pending_offers_retry_cta',
  'pending_retry_cta',
  'profile_close',
  'profile_edit_back',
  'profile_edit_change_avatar_cta',
  'profile_edit_remove_avatar_cta',
  'profile_edit_save_cta',
  'profile_name_skip_cta',
  'profile_name_submit_cta',
  'profile_unavailable_back',
  'prohibited_acknowledgment_sheet_acknowledge_cta',
  'prohibited_acknowledgment_sheet_retry_cta',
  'prohibited_item_report_attach_photo',
  'prohibited_item_report_back',
  'prohibited_item_report_submit',
  'rating_submit_cta',
  'receipt_confirm_cta',
  'receipt_confirm_error',
  'receipt_not_yet_cta',
  'receipt_proof_photo',
  'receipt_proof_viewer_close',
  'receipt_proof_zoom_cta',
  'register_trust_note',
  'replies_accept_cta',
  'replies_check_offers_cta',
  'replies_retry_cta',
  'request_feed_back',
  'request_feed_retry_cta',
  'request_summary_back',
  'request_summary_edit_description',
  'request_summary_submit',
  'request_summary_unavailable_back',
  'request_summary_voice_play',
  'request_type_back',
  'request_type_continue_cta',
  'request_type_tiers_retry',
  'reviews_back',
  'reviews_load_more_retry',
  'reviews_retry_cta',
  'setpw_back',
  'setpw_confirm_visibility_toggle',
  'setpw_new_visibility_toggle',
  'setpw_submit_cta',
  'settings-profile-row',
  'settings-row-become-jeeber',
  'settings-row-notifications-manage',
  'settings_back',
  'settings_delete_account_row',
  'settings_language_ar_option',
  'settings_language_en_option',
  'settings_notifications_offers_toggle',
  'settings_notifications_ratings_toggle',
  'settings_notifications_status_toggle',
  'settings_open_diagnostics',
  'settings_sign_out_row',
  'settings_unregister_jeeber',
  'shell_tab_dashboard',
  'shell_tab_deliver',
  'shell_tab_delivery',
  'shell_tab_earnings',
  'shell_tab_profile',
  'shell_tab_requests',
  'social_collision_sheet_dismiss_cta',
  'super_login_plus_button',
  'support_attach',
  'support_back',
  'support_category',
  'support_confirmation',
  'support_confirmation_back_cta',
  'support_dispute_link',
  'support_error',
  'support_reply_attach',
  'support_reply_send',
  'support_reply_upload_progress',
  'support_retry_cta',
  'support_root',
  'support_submit_cta',
  'support_submitting',
  'support_success',
  'support_success_done_cta',
  'support_thread_back',
  'support_thread_closed',
  'support_thread_conflict',
  'support_thread_empty',
  'support_thread_load_more',
  'support_thread_loading',
  'support_thread_pagination_error',
  'support_thread_partial_evidence',
  'support_thread_request',
  'support_thread_retry_cta',
  'support_thread_root',
  'support_thread_status',
  'support_upload_progress',
  'support_view_thread_cta',
  'tier_selection_confirm_cta',
  'tracking_at_door_code',
  'tracking_back',
  'tracking_cancelled_state',
  'tracking_courier_card',
  'tracking_deadline_label',
  'tracking_dispute_cta',
  'tracking_distance_label',
  'tracking_error_state',
  'tracking_eta_label',
  'tracking_expired_state',
  'tracking_handover_code_row',
  'tracking_map',
  'tracking_noshow_cta',
  'tracking_noshow_keep_cta',
  'tracking_noshow_reassign_cta',
  'tracking_noshow_rebroadcast_cta',
  'tracking_noshow_sheet',
  'tracking_progress_stepper',
  'tracking_root',
  'tracking_status_panel',
  'tracking_stepper',
  'tracking_under_review_state',
  'txn_detail_back',
  'txn_detail_dispute_link',
  'txn_detail_fee_rate',
  'txn_detail_order_link',
  'unregister_jeeber_cancel_cta',
  'unregister_jeeber_confirm_cta',
  'unregister_jeeber_confirm_sheet',
  'voice_request_back',
  'voice_request_cancel_button',
  'voice_request_discard_button',
  'voice_request_mic_button',
  'voice_request_playback_progress',
  'voice_request_playback_toggle',
  'voice_request_record_another_button',
  'voice_request_recording_waveform',
  'voice_request_retry_button',
  'voice_request_retry_upload_button',
  'voice_request_send_button',
  'voice_request_type_button',
  'voice_request_upload_error_state',
  'waiting_back',
  'waiting_cancel_cta',
  'waiting_retarget_cta',
  'waiting_review_offers_cta',
  'waiting_terminal_home_cta',
  'walkthrough_skip_cta',
  'wallet_activity_back',
  'wallet_activity_empty',
  'wallet_activity_error',
  'wallet_activity_load_more',
  'wallet_activity_load_more_retry',
  'wallet_activity_loading',
  'wallet_activity_retry_cta',
  'wallet_activity_root',
  'wallet_affordability_card',
  'wallet_available_balance',
  'wallet_back',
  'wallet_cash_disclaimer',
  'wallet_earnings_row',
  'wallet_gift_badge',
  'wallet_how_fees_explainer',
  'wallet_how_fees_work',
  'wallet_hub_root',
  'wallet_kyc_pending_banner',
  'wallet_load_error',
  'wallet_loading',
  'wallet_reserved_now',
  'wallet_see_all_activity',
  'wallet_topup_cta',
  '_request_empty_state_root',
  '_splash_logo',
  '_splash_screen',
  '_super_login_sheet',
  'account_status_banner',
  'account_status_load_error',
  'account_status_loading',
  'account_status_reason',
  'account_status_retry_cta',
  'account_status_root',
  'active_delivery_error',
  'active_delivery_loading',
  'availability_card',
  'biometric_prompt_root',
  'biometric_unlock_prompt',
  'charge_info_auto_update_note',
  'charge_info_fee_note',
  'charge_info_root',
  'charge_info_whatsapp_note',
  'client_home_root',
  'client_home_voice_discard',
  'client_home_voice_status',
  'client_home_voice_timer',
  'client_unreachable_root',
  'compose_tier_change',
  'compose_tier_sheet',
  'customer_profile_avatar',
  'customer_profile_load_error',
  'customer_profile_load_retry',
  'customer_profile_loading',
  'customer_profile_name',
  'customer_profile_rating',
  'customer_profile_root',
  'delivery-rating-summary',
  'delivery_completed_state',
  'delivery_man_profile_name',
  'delivery_man_profile_screen_root',
  'delivery_status_root',
  'devtool.session_logs.screen',
  'diag_refresh',
  'diagnostics_back',
  'diagnostics_disabled',
  'diagnostics_error',
  'diagnostics_loading',
  'diagnostics_retry',
  'diagnostics_screen_root',
  'diagnostics_sessions_empty',
  'dm_onboarding_progress',
  'dm_onboarding_service_area_root',
  'earnings_breakdown_empty',
  'earnings_dashboard_root',
  'earnings_deliveries_count',
  'earnings_empty',
  'earnings_error',
  'earnings_fees_paid',
  'earnings_loading',
  'earnings_member_since',
  'earnings_net_per_offer',
  'earnings_tab_session_loading',
  'earnings_tab_unavailable',
  'earnings_total_cash',
  'funding_explainer',
  'funding_reserved_now_amount',
  'goods_cost_cash_note',
  'goods_cost_root',
  'in_progress_empty_state',
  'in_progress_error_state',
  'in_progress_loading_state',
  'insufficient_balance_available_amount',
  'insufficient_balance_needed_amount',
  'insufficient_balance_sheet',
  'jeeb_verified_badge',
  'jeeber-request-detail-loading',
  'jeeber-request-detail-make-offer',
  'jeeber_active_deliveries',
  'jeeber_active_deliveries_section',
  'jeeber_active_deliveries_view_all',
  'jeeber_dashboard_empty_state',
  'jeeber_earnings_empty_state',
  'jeeber_feed_empty_state',
  'jeeber_feed_empty_view_empty_state',
  'jeeber_feed_offline_empty_state',
  'jeeber_home_root',
  'jeeber_pending_offers_empty_state',
  'jeeber_pending_offers_root',
  'jeeber_request_detail_description',
  'jeeber_request_detail_loading_state',
  'jeeber_request_unavailable',
  'jeeber_tab_empty_state_cta',
  'kyc_id_type_picker',
  'kyc_rejected_authority_loading',
  'kyc_rejected_reason',
  'kyc_rejected_root',
  'kyc_review_note',
  'kyc_status_loading',
  'kyc_status_root',
  'kyc_status_view_rejection',
  'kyc_tos_document_sheet',
  'kyc_wizard_root',
  'kyc_wizard_schema_error',
  'kyc_wizard_schema_loading',
  'kyc_wizard_tos_error',
  'language_settings_root',
  'live_settings_error',
  'live_settings_loading',
  'live_settings_retry_cta',
  'live_settings_sign_out_cta',
  'login_social_apple',
  'login_social_google',
  'mark_delivered_cash_note',
  'mark_delivered_note_tile',
  'mark_delivered_root',
  'mutual_rating_blind_note',
  'mutual_rating_error',
  'mutual_rating_loading',
  'mutual_rating_stars',
  'notif_prefs_load_error',
  'notif_prefs_loading',
  'notif_prefs_push_only_note',
  'notif_prefs_root',
  'notif_prefs_transactional_lock_icon',
  'notification_permission_prompt',
  'notifications_empty',
  'notifications_error',
  'notifications_loading',
  'notifications_root',
  'offer_card_no_ratings',
  'offer_composer_eta_dropdown',
  'offer_composer_fee_line',
  'offer_composer_insufficient_reason',
  'offer_composer_net_line',
  'offer_composer_offer_line',
  'offer_composer_root',
  'offer_kyc_gate',
  'offer_review_empty_state',
  'offer_review_list_root',
  'offer_review_only_one_note',
  'offer_review_sort_best',
  'offer_review_sort_price',
  'offer_review_sort_rating',
  'offer_review_window_strip',
  'offer_status_info_sheet',
  'onboarding_headline',
  'onboarding_language_ar',
  'onboarding_language_en',
  'onboarding_page_dots',
  'onboarding_root',
  'onboarding_wordmark',
  'order-detail-root',
  'order-detail-status-active',
  'order_detail_loading',
  'order_history_error',
  'order_history_loading',
  'order_history_loading_more',
  'order_history_root',
  'order_summary_cash_label',
  'order_summary_empty',
  'order_summary_error',
  'order_summary_eta',
  'order_summary_item',
  'order_summary_jeeber_name',
  'order_summary_loading',
  'order_summary_pinned',
  'order_summary_price',
  'order_summary_root',
  'order_summary_status',
  'order_summary_tier',
  'pending_offer_awaiting_label',
  'profile_edit_loading',
  'profile_name_root',
  'profile_unavailable_note',
  'profile_unavailable_root',
  'profile_view_all_reviews',
  'prohibited_item_report_root',
  'rating_root',
  'receipt_cash_to_jeeber_label',
  'receipt_load_error',
  'receipt_loading',
  'receipt_prompt',
  'receipt_proof_viewer_root',
  'registration_root',
  'request_feed_empty_state',
  'request_feed_error_state',
  'request_feed_loading_state',
  'request_feed_root',
  'request_summary_change_route',
  'request_summary_change_tier',
  'request_summary_loading',
  'request_summary_root',
  'request_summary_unavailable_note',
  'request_summary_unavailable_root',
  'reviews_aggregate',
  'reviews_empty',
  'reviews_error',
  'reviews_hidden_score_note',
  'reviews_load_more',
  'reviews_loading',
  'reviews_new_badge',
  'reviews_root',
  'service_area_map_pin',
  'setpw_root',
  'setpw_validation_error',
  'settings_analytics_disclosure',
  'settings_analytics_section',
  'settings_analytics_toggle',
  'social_collision_sheet',
  'super_login_plus_picker',
  'super_login_plus_picker_error',
  'super_login_plus_picker_loading',
  'super_login_plus_picker_no_matches',
  'tier_selection_root',
  'tracking_position_notice',
  'txn_detail',
  'txn_detail_amount',
  'txn_detail_fee_percentage_label',
  'txn_detail_order_ref',
  'txn_detail_pinned_price',
  'txn_detail_root',
  'txn_detail_type_label',
  'txn_detail_type_summary',
  'voice_request_blocked_state',
  'voice_request_root',
  'voice_request_timer',
  'waiting_countdown',
  'waiting_error_state',
  'waiting_no_coverage_state',
  'waiting_request_description',
  'waiting_terminal_state',
  'funding_wallet_error',
  'funding_wallet_loading',
  'jeeber_feed_root',
  'kyc_status_poll_expired',
  'support_thread_error',
  'support_thread_offline',
  'support_thread_refresh_error',
  'support_thread_send_error',
  'walkthrough_get_started_cta',
  'walkthrough_next_cta',
  '_request_empty_state_avatar',
  'client_home_voice_blocked_dismiss',
  'client_home_voice_tier_dismiss',
  'delivery_man_profile_availability',
  'delivery_man_profile_rating_summary',
  'delivery_register_now_cta',
  'dm_onboarding_continue',
  'in_progress_empty_title',
  'jeeber_feed_filter_apply',
  'jeeber_feed_filter_clear',
  'jeeber_feed_filter_pill_query_clear',
  'jeeber_feed_filter_pill_tier_clear',
  'jeeber_home_avatar',
  'kyc_submitting_title',
  'offer_composer_order_ref',
  'offer_composer_price_decrement',
  'offer_composer_price_increment',
  'offer_composer_reserve_note',
  'offer_review_empty_title',
  'order-detail-escalate',
  'order-detail-rate',
  'order-detail-receipt',
  'order-detail-status-cancelled',
  'order-detail-status-delivered',
  'order-detail-track',
  'orders_filter_apply',
  'orders_filter_clear',
  'profile_score',
  'tracking_cancelled_home_cta',
  'tracking_expired_home_cta',
  'waiting_notified_count',
};

/// Sensitive-named static actions retain a diagnostic-safe alias without
/// preserving the credential or address vocabulary from their source ID.
const Map<String, String> kAuditedStaticInteractionAliases = <String, String>{
  'charge_info_whatsapp_cta': 'charge_info_messaging_cta',
  'chat_detail_attach_button': 'conversation_detail_attach_button',
  'chat_detail_send_button': 'conversation_detail_send_button',
  'client_location_add_new': 'client_place_add_new',
  'client_location_loading': 'client_place_loading',
  'in_progress_empty_body': 'in_progress_empty_copy',
  'offer_review_empty_body': 'offer_review_empty_copy',
  'order-detail-chat': 'order-detail-conversation',
  'order-detail-otp': 'order-detail-verification',
  'order_chat_composer_send': 'order_conversation_composer_send',
  'otp_handover_code_display': 'verification_handover_code_display',
  'customer_profile_addresses_row': 'customer_profile_saved_places_row',
  'customer_profile_password_row': 'customer_profile_security_row',
  'order_summary_open_chat': 'order_summary_open_conversation',
  'active_delivery_gps_permission_banner':
      'active_delivery_place_permission_banner',
  'active_delivery_gps_permission_cta': 'active_delivery_place_permission_cta',
  'address_detail_form_root': 'place_detail_form_root',
  'address_form_back': 'place_form_back',
  'address_form_edit_pin_cta': 'place_form_edit_pin_cta',
  'address_form_map_pin': 'place_form_map_pin',
  'address_form_pin_coordinate': 'place_form_pin_place',
  'address_form_save_cta': 'place_form_save_cta',
  'biometric_unlock_use_password_link': 'biometric_unlock_use_security_link',
  'capture_location_address_card': 'capture_place_summary_card',
  'capture_location_back': 'capture_place_back',
  'capture_location_gps_denied': 'capture_place_signal_denied',
  'capture_location_gps_denied_cta': 'capture_place_signal_denied_cta',
  'capture_location_map': 'capture_place_map',
  'capture_location_my_location': 'capture_place_my_place',
  'capture_location_pin': 'capture_place_pin',
  'capture_location_pin_callout': 'capture_place_pin_callout',
  'capture_location_pin_cta': 'capture_place_pin_cta',
  'capture_location_root': 'capture_place_root',
  'capture_location_zoom_in': 'capture_place_zoom_in',
  'capture_location_zoom_out': 'capture_place_zoom_out',
  'chat_detail_avatar': 'conversation_detail_avatar',
  'chat_detail_back_button': 'conversation_detail_back_button',
  'chat_detail_date_separator': 'conversation_detail_date_separator',
  'chat_detail_message_delivered': 'conversation_detail_message_delivered',
  'chat_detail_message_failed': 'conversation_detail_message_failed',
  'chat_detail_message_list': 'conversation_detail_message_list',
  'chat_detail_message_read': 'conversation_detail_message_read',
  'chat_detail_message_sending': 'conversation_detail_message_sending',
  'chat_detail_message_sent': 'conversation_detail_message_sent',
  'chat_detail_offer_only_one_note': 'conversation_detail_offer_only_one_note',
  'chat_detail_resolution_retry': 'conversation_detail_resolution_retry',
  'chat_detail_root': 'conversation_detail_root',
  'chat_dm_fee_banner': 'conversation_dm_fee_banner',
  'chat_dm_fee_banner_dismiss': 'conversation_dm_fee_banner_dismiss',
  'chat_dm_order_picked_button': 'conversation_dm_order_picked_button',
  'chat_history_error': 'conversation_history_error',
  'chat_history_error_retry': 'conversation_history_error_retry',
  'chat_resolution_error': 'conversation_resolution_error',
  'chat_start_active_delivery_cta': 'conversation_start_active_delivery_cta',
  'client_location_back': 'client_place_back',
  'client_location_option_current': 'client_place_option_current',
  'client_location_root': 'client_place_root',
  'client_location_saved_places_row': 'client_place_saved_places_row',
  'client_location_session_loading': 'client_place_session_loading',
  'client_otp_rate_now': 'client_verification_rate_now',
  'client_unreachable_chat_cta': 'client_unreachable_conversation_cta',
  'current_location_gps_primary_cta': 'current_place_signal_primary_cta',
  'current_location_gps_recovery': 'current_place_signal_recovery',
  'current_location_gps_resolved': 'current_place_signal_resolved',
  'current_location_gps_resolving': 'current_place_signal_resolving',
  'current_location_gps_retry_cta': 'current_place_signal_retry_cta',
  'dm_onboarding_address_root': 'dm_onboarding_place_root',
  'dm_onboarding_location_value': 'dm_onboarding_place_value',
  'location_select_confirm_cta': 'place_select_confirm_cta',
  'location_select_new_location_cta': 'place_select_new_place_cta',
  'location_select_saved_addresses_error': 'place_select_saved_places_error',
  'location_select_saved_addresses_row': 'place_select_saved_places_row',
  'mark_delivered_open_chat_cta': 'mark_delivered_open_conversation_cta',
  'mark_delivered_otp_submit': 'mark_delivered_verification_submit',
  'order_chat_cash_label': 'order_conversation_cash_label',
  'order_chat_open_dispute': 'order_conversation_open_dispute',
  'order_chat_pinned_summary': 'order_conversation_pinned_summary',
  'order_chat_quick_reply_door': 'order_conversation_quick_reply_door',
  'order_chat_quick_reply_home': 'order_conversation_quick_reply_home',
  'order_chat_quick_reply_row': 'order_conversation_quick_reply_row',
  'order_chat_quick_reply_thanks': 'order_conversation_quick_reply_thanks',
  'order_chat_request_description': 'order_conversation_request_description',
  'order_chat_root': 'order_conversation_root',
  'order_chat_summary_expand': 'order_conversation_summary_expand',
  'order_chat_summary_reference': 'order_conversation_summary_reference',
  'order_chat_track_cta': 'order_conversation_track_cta',
  'order_chat_view_summary_link': 'order_conversation_view_summary_link',
  'otp_done_rate_now': 'verification_done_rate_now',
  'otp_handover_arrival': 'verification_handover_arrival',
  'otp_handover_back': 'verification_handover_back',
  'otp_handover_dispute': 'verification_handover_dispute',
  'otp_handover_error': 'verification_handover_error',
  'otp_handover_loading': 'verification_handover_loading',
  'otp_handover_root': 'verification_handover_root',
  'otp_handover_send_sms': 'verification_handover_send_sms',
  'otp_handover_submit': 'verification_handover_submit',
  'otp_sms_fallback': 'verification_sms_fallback',
  'otp_sms_resend': 'verification_sms_resend',
  'password_back': 'security_back',
  'password_confirm_visibility_toggle': 'security_confirm_visibility_toggle',
  'password_mismatch_error': 'security_mismatch_error',
  'password_new_visibility_toggle': 'security_new_visibility_toggle',
  'password_security_root': 'security_security_root',
  'password_set_entry': 'security_set_entry',
  'password_strength_error': 'security_strength_error',
  'password_submit_cta': 'security_submit_cta',
  'phone_otp_back_cta': 'contact_verification_back_cta',
  'phone_otp_change_phone_cta': 'contact_verification_change_contact_cta',
  'phone_otp_lockout_banner': 'contact_verification_lockout_banner',
  'phone_otp_resend_cta': 'contact_verification_resend_cta',
  'phone_otp_resend_timer': 'contact_verification_resend_timer',
  'phone_otp_root': 'contact_verification_root',
  'phone_otp_verify_cta': 'contact_verification_verify_cta',
  'register_phone_helper': 'register_contact_helper',
  'register_phone_label': 'register_contact_label',
  'register_phone_submit_cta': 'register_contact_submit_cta',
  'request_type_change_location_button': 'request_type_change_place_button',
  'request_type_current_location_label': 'request_type_current_place_label',
  'saved_address_add_cta': 'saved_place_add_cta',
  'saved_address_default_badge': 'saved_place_default_badge',
  'saved_address_delete_cancel_cta': 'saved_place_delete_cancel_cta',
  'saved_address_delete_confirm_cta': 'saved_place_delete_confirm_cta',
  'saved_address_delete_confirm_sheet': 'saved_place_delete_confirm_sheet',
  'saved_address_error_retry_cta': 'saved_place_error_retry_cta',
  'saved_address_sheet_delete_cta': 'saved_place_sheet_delete_cta',
  'saved_address_sheet_edit_cta': 'saved_place_sheet_edit_cta',
  'saved_addresses_back': 'saved_places_back',
  'saved_addresses_placeholder': 'saved_places_placeholder',
  'service_area_select_location': 'service_area_select_place',
  'settings_notifications_chat_toggle':
      'settings_notifications_conversation_toggle',
  'settings_open_addresses': 'settings_open_places',
  'tracking_otp_cta': 'tracking_verification_cta',
  'voice_request_live_transcript': 'voice_request_live_voice_copy',
  'voice_transcript_audio_toggle': 'voice_copy_audio_toggle',
  'voice_transcript_back': 'voice_copy_back',
  'voice_transcript_confirm_button': 'voice_copy_confirm_button',
  'voice_transcript_edit_button': 'voice_copy_edit_button',
  'voice_transcript_language_chip': 'voice_copy_language_chip',
  'voice_transcript_quick_add_brand': 'voice_copy_quick_add_brand',
  'voice_transcript_quick_add_budget': 'voice_copy_quick_add_budget',
  'voice_transcript_quick_add_quantity': 'voice_copy_quick_add_quantity',
  'voice_transcript_re_record_button': 'voice_copy_re_record_button',
  'voice_transcript_retry_button': 'voice_copy_retry_button',
  'voice_transcript_root': 'voice_copy_root',
  'voice_transcript_save_edit_button': 'voice_copy_save_edit_button',
  'voice_transcript_scrubber': 'voice_copy_scrubber',
  'voice_transcript_transcript_text': 'voice_copy_preview_text',
};

/// Compile-time identifiers intentionally collapsed to `<redacted>` because
/// retaining them could expose typed-field focus or reconstruct secret input.
const Set<String> kExplicitlyRedactedStaticInteractionIdentifiers = <String>{
  '_super_login_passcode',
  '_super_login_user_id',
  'address_form_building',
  'address_form_cod_phone',
  'address_form_delivery_notes',
  'address_form_floor_apt',
  'address_form_label',
  'cancellation_other_field',
  'chat_detail_message_input',
  'compose_description_input',
  'devtool.scenarioUsers.username',
  'devtool.walletFunding.amount',
  'dispute_comment_field',
  'dm_onboarding_address_country_field',
  'dm_onboarding_address_field',
  'dm_onboarding_address_state_field',
  'dm_onboarding_address_street_field',
  'feedback_comment_field',
  'goods_cost_amount_field',
  'jeeber_feed_search_field',
  'kyc_id_number_input',
  'mark_delivered_note_field',
  'mark_delivered_otp_input',
  'mutual_rating_comment',
  'offer_composer_note_field',
  'offer_composer_price_field',
  'order_chat_composer_input',
  'otp_handover_input',
  'password_confirm_field',
  'password_current_field',
  'password_new_field',
  'phone_otp_input',
  'profile_edit_name_field',
  'profile_name_input',
  'prohibited_item_report_description',
  'recipient_phone_input',
  'register_phone_field',
  'setpw_confirm_field',
  'setpw_new_field',
  'super_login_plus_picker_search',
  'support_body',
  'support_order_link',
  'support_reply_composer',
  'voice_transcript_text_field',
};
