// Country names and calling-code metadata are adapted from intl_phone_field
// 3.2.0 (MIT), which cites the public ITU calling-code table.
//
// Copyright (c) 2021 Vansh Goel
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to
// deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
// sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

/// Registration-owned metadata needed to render and validate a country option.
class RegistrationCountryMetadata {
  const RegistrationCountryMetadata({
    required this.code,
    required this.dialCode,
    required this.flag,
    required this.englishName,
    required this.arabicName,
    required this.minNationalDigits,
    required this.maxNationalDigits,
    this.nationalPrefix,
  });

  final String code;
  final String dialCode;
  final String flag;
  final String englishName;
  final String arabicName;
  final int minNationalDigits;
  final int maxNationalDigits;
  final String? nationalPrefix;

  String localizedName(String languageCode) =>
      languageCode == 'ar' ? arabicName : englishName;
}

/// Complete ISO territory catalog exposed by the registration country picker.
abstract final class RegistrationCountryCatalog {
  static const String defaultCountryCode = 'LB';

  static const List<RegistrationCountryMetadata> all =
      <RegistrationCountryMetadata>[
        RegistrationCountryMetadata(
          code: "AF",
          dialCode: "+93",
          flag: "🇦🇫",
          englishName: "Afghanistan",
          arabicName: "أفغانستان",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "AX",
          dialCode: "+358",
          flag: "🇦🇽",
          englishName: "Åland Islands",
          arabicName: "جزر أولاند",
          minNationalDigits: 4,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "AL",
          dialCode: "+355",
          flag: "🇦🇱",
          englishName: "Albania",
          arabicName: "ألبانيا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "DZ",
          dialCode: "+213",
          flag: "🇩🇿",
          englishName: "Algeria",
          arabicName: "الجزائر",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "AS",
          dialCode: "+1684",
          flag: "🇦🇸",
          englishName: "American Samoa",
          arabicName: "ساموا الأمريكية",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "AD",
          dialCode: "+376",
          flag: "🇦🇩",
          englishName: "Andorra",
          arabicName: "أندورا",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "AO",
          dialCode: "+244",
          flag: "🇦🇴",
          englishName: "Angola",
          arabicName: "أنغولا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "AI",
          dialCode: "+1264",
          flag: "🇦🇮",
          englishName: "Anguilla",
          arabicName: "أنغويلا",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "AQ",
          dialCode: "+672",
          flag: "🇦🇶",
          englishName: "Antarctica",
          arabicName: "القارة القطبية الجنوبية",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "AG",
          dialCode: "+1268",
          flag: "🇦🇬",
          englishName: "Antigua and Barbuda",
          arabicName: "أنتيغوا وباربودا",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "AR",
          dialCode: "+54",
          flag: "🇦🇷",
          englishName: "Argentina",
          arabicName: "الأرجنتين",
          minNationalDigits: 12,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "AM",
          dialCode: "+374",
          flag: "🇦🇲",
          englishName: "Armenia",
          arabicName: "أرمينيا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "AW",
          dialCode: "+297",
          flag: "🇦🇼",
          englishName: "Aruba",
          arabicName: "أروبا",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "AU",
          dialCode: "+61",
          flag: "🇦🇺",
          englishName: "Australia",
          arabicName: "أستراليا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "AT",
          dialCode: "+43",
          flag: "🇦🇹",
          englishName: "Austria",
          arabicName: "النمسا",
          minNationalDigits: 13,
          maxNationalDigits: 13,
        ),
        RegistrationCountryMetadata(
          code: "AZ",
          dialCode: "+994",
          flag: "🇦🇿",
          englishName: "Azerbaijan",
          arabicName: "أذربيجان",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "BS",
          dialCode: "+1242",
          flag: "🇧🇸",
          englishName: "Bahamas",
          arabicName: "باهاماس",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "BH",
          dialCode: "+973",
          flag: "🇧🇭",
          englishName: "Bahrain",
          arabicName: "البحرين",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "BD",
          dialCode: "+880",
          flag: "🇧🇩",
          englishName: "Bangladesh",
          arabicName: "بنغلاديش",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "BB",
          dialCode: "+1246",
          flag: "🇧🇧",
          englishName: "Barbados",
          arabicName: "باربادوس",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "BY",
          dialCode: "+375",
          flag: "🇧🇾",
          englishName: "Belarus",
          arabicName: "بيلاروس",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "BE",
          dialCode: "+32",
          flag: "🇧🇪",
          englishName: "Belgium",
          arabicName: "بلجيكا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "BZ",
          dialCode: "+501",
          flag: "🇧🇿",
          englishName: "Belize",
          arabicName: "بليز",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "BJ",
          dialCode: "+229",
          flag: "🇧🇯",
          englishName: "Benin",
          arabicName: "بنين",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "BM",
          dialCode: "+1441",
          flag: "🇧🇲",
          englishName: "Bermuda",
          arabicName: "برمودا",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "BT",
          dialCode: "+975",
          flag: "🇧🇹",
          englishName: "Bhutan",
          arabicName: "بوتان",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "BO",
          dialCode: "+591",
          flag: "🇧🇴",
          englishName: "Bolivia, Plurinational State of bolivia",
          arabicName: "بوليفيا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "BA",
          dialCode: "+387",
          flag: "🇧🇦",
          englishName: "Bosnia and Herzegovina",
          arabicName: "البوسنة والهرسك",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "BW",
          dialCode: "+267",
          flag: "🇧🇼",
          englishName: "Botswana",
          arabicName: "بوتسوانا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "BV",
          dialCode: "+47",
          flag: "🇧🇻",
          englishName: "Bouvet Island",
          arabicName: "جزيرة بوفيه",
          minNationalDigits: 4,
          maxNationalDigits: 13,
        ),
        RegistrationCountryMetadata(
          code: "BR",
          dialCode: "+55",
          flag: "🇧🇷",
          englishName: "Brazil",
          arabicName: "البرازيل",
          minNationalDigits: 11,
          maxNationalDigits: 11,
        ),
        RegistrationCountryMetadata(
          code: "IO",
          dialCode: "+246",
          flag: "🇮🇴",
          englishName: "British Indian Ocean Territory",
          arabicName: "إقليم المحيط الهندي البريطاني",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "BN",
          dialCode: "+673",
          flag: "🇧🇳",
          englishName: "Brunei Darussalam",
          arabicName: "بروناي",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "BG",
          dialCode: "+359",
          flag: "🇧🇬",
          englishName: "Bulgaria",
          arabicName: "بلغاريا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "BF",
          dialCode: "+226",
          flag: "🇧🇫",
          englishName: "Burkina Faso",
          arabicName: "بوركينا فاسو",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "BI",
          dialCode: "+257",
          flag: "🇧🇮",
          englishName: "Burundi",
          arabicName: "بوروندي",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "KH",
          dialCode: "+855",
          flag: "🇰🇭",
          englishName: "Cambodia",
          arabicName: "كمبوديا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "CM",
          dialCode: "+237",
          flag: "🇨🇲",
          englishName: "Cameroon",
          arabicName: "الكاميرون",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "CA",
          dialCode: "+1",
          flag: "🇨🇦",
          englishName: "Canada",
          arabicName: "كندا",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "KY",
          dialCode: "+345",
          flag: "🇰🇾",
          englishName: "Cayman Islands",
          arabicName: "جزر كايمان",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "CF",
          dialCode: "+236",
          flag: "🇨🇫",
          englishName: "Central African Republic",
          arabicName: "جمهورية أفريقيا الوسطى",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "TD",
          dialCode: "+235",
          flag: "🇹🇩",
          englishName: "Chad",
          arabicName: "تشاد",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "CL",
          dialCode: "+56",
          flag: "🇨🇱",
          englishName: "Chile",
          arabicName: "تشيلي",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "CN",
          dialCode: "+86",
          flag: "🇨🇳",
          englishName: "China",
          arabicName: "الصين",
          minNationalDigits: 11,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "CX",
          dialCode: "+61",
          flag: "🇨🇽",
          englishName: "Christmas Island",
          arabicName: "جزيرة عيد الميلاد",
          minNationalDigits: 4,
          maxNationalDigits: 13,
        ),
        RegistrationCountryMetadata(
          code: "CC",
          dialCode: "+61",
          flag: "🇨🇨",
          englishName: "Cocos (Keeling) Islands",
          arabicName: "جزر كوكوس",
          minNationalDigits: 4,
          maxNationalDigits: 13,
        ),
        RegistrationCountryMetadata(
          code: "CO",
          dialCode: "+57",
          flag: "🇨🇴",
          englishName: "Colombia",
          arabicName: "كولومبيا",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "KM",
          dialCode: "+269",
          flag: "🇰🇲",
          englishName: "Comoros",
          arabicName: "جزر القمر",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "CG",
          dialCode: "+242",
          flag: "🇨🇬",
          englishName: "Congo",
          arabicName: "جمهورية الكونغو",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "CD",
          dialCode: "+243",
          flag: "🇨🇩",
          englishName: "Congo, The Democratic Republic of the Congo",
          arabicName: "جمهورية الكونغو الديمقراطية",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "CK",
          dialCode: "+682",
          flag: "🇨🇰",
          englishName: "Cook Islands",
          arabicName: "جزر كوك",
          minNationalDigits: 5,
          maxNationalDigits: 5,
        ),
        RegistrationCountryMetadata(
          code: "CR",
          dialCode: "+506",
          flag: "🇨🇷",
          englishName: "Costa Rica",
          arabicName: "كوستاريكا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "CI",
          dialCode: "+225",
          flag: "🇨🇮",
          englishName: "Côte d'Ivoire",
          arabicName: "ساحل العاج",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "HR",
          dialCode: "+385",
          flag: "🇭🇷",
          englishName: "Croatia",
          arabicName: "كرواتيا",
          minNationalDigits: 12,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "CU",
          dialCode: "+53",
          flag: "🇨🇺",
          englishName: "Cuba",
          arabicName: "كوبا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "CY",
          dialCode: "+357",
          flag: "🇨🇾",
          englishName: "Cyprus",
          arabicName: "قبرص",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "CZ",
          dialCode: "+420",
          flag: "🇨🇿",
          englishName: "Czech Republic",
          arabicName: "جمهورية التشيك",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "DK",
          dialCode: "+45",
          flag: "🇩🇰",
          englishName: "Denmark",
          arabicName: "الدنمارك",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "DJ",
          dialCode: "+253",
          flag: "🇩🇯",
          englishName: "Djibouti",
          arabicName: "جيبوتي",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "DM",
          dialCode: "+1767",
          flag: "🇩🇲",
          englishName: "Dominica",
          arabicName: "دومينيكا",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "DO",
          dialCode: "+1",
          flag: "🇩🇴",
          englishName: "Dominican Republic",
          arabicName: "جمهورية الدومينيكان",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "EC",
          dialCode: "+593",
          flag: "🇪🇨",
          englishName: "Ecuador",
          arabicName: "الإكوادور",
          minNationalDigits: 8,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "EG",
          dialCode: "+20",
          flag: "🇪🇬",
          englishName: "Egypt",
          arabicName: "مصر",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "SV",
          dialCode: "+503",
          flag: "🇸🇻",
          englishName: "El Salvador",
          arabicName: "السلفادور",
          minNationalDigits: 11,
          maxNationalDigits: 11,
        ),
        RegistrationCountryMetadata(
          code: "GQ",
          dialCode: "+240",
          flag: "🇬🇶",
          englishName: "Equatorial Guinea",
          arabicName: "غينيا الاستوائية",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "ER",
          dialCode: "+291",
          flag: "🇪🇷",
          englishName: "Eritrea",
          arabicName: "إريتريا",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "EE",
          dialCode: "+372",
          flag: "🇪🇪",
          englishName: "Estonia",
          arabicName: "إستونيا",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "ET",
          dialCode: "+251",
          flag: "🇪🇹",
          englishName: "Ethiopia",
          arabicName: "إثيوبيا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "FK",
          dialCode: "+500",
          flag: "🇫🇰",
          englishName: "Falkland Islands (Malvinas)",
          arabicName: "جزر فوكلاند",
          minNationalDigits: 5,
          maxNationalDigits: 5,
        ),
        RegistrationCountryMetadata(
          code: "FO",
          dialCode: "+298",
          flag: "🇫🇴",
          englishName: "Faroe Islands",
          arabicName: "جزر فارو",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "FJ",
          dialCode: "+679",
          flag: "🇫🇯",
          englishName: "Fiji",
          arabicName: "فيجي",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "FI",
          dialCode: "+358",
          flag: "🇫🇮",
          englishName: "Finland",
          arabicName: "فنلندا",
          minNationalDigits: 12,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "FR",
          dialCode: "+33",
          flag: "🇫🇷",
          englishName: "France",
          arabicName: "فرنسا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "GF",
          dialCode: "+594",
          flag: "🇬🇫",
          englishName: "French Guiana",
          arabicName: "غويانا الفرنسية",
          minNationalDigits: 4,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "PF",
          dialCode: "+689",
          flag: "🇵🇫",
          englishName: "French Polynesia",
          arabicName: "بولينزيا الفرنسية",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "TF",
          dialCode: "+262",
          flag: "🇹🇫",
          englishName: "French Southern Territories",
          arabicName: "أراض فرنسية جنوبية وأنتارتيكية",
          minNationalDigits: 4,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "GA",
          dialCode: "+241",
          flag: "🇬🇦",
          englishName: "Gabon",
          arabicName: "الغابون",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "GM",
          dialCode: "+220",
          flag: "🇬🇲",
          englishName: "Gambia",
          arabicName: "غامبيا",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "GE",
          dialCode: "+995",
          flag: "🇬🇪",
          englishName: "Georgia",
          arabicName: "جورجيا",
          minNationalDigits: 8,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "DE",
          dialCode: "+49",
          flag: "🇩🇪",
          englishName: "Germany",
          arabicName: "ألمانيا",
          minNationalDigits: 9,
          maxNationalDigits: 13,
        ),
        RegistrationCountryMetadata(
          code: "GH",
          dialCode: "+233",
          flag: "🇬🇭",
          englishName: "Ghana",
          arabicName: "غانا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "GI",
          dialCode: "+350",
          flag: "🇬🇮",
          englishName: "Gibraltar",
          arabicName: "جبل طارق",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "GR",
          dialCode: "+30",
          flag: "🇬🇷",
          englishName: "Greece",
          arabicName: "اليونان",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "GL",
          dialCode: "+299",
          flag: "🇬🇱",
          englishName: "Greenland",
          arabicName: "جرينلاند",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "GD",
          dialCode: "+1473",
          flag: "🇬🇩",
          englishName: "Grenada",
          arabicName: "غرينادا",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "GP",
          dialCode: "+590",
          flag: "🇬🇵",
          englishName: "Guadeloupe",
          arabicName: "غوادلوب",
          minNationalDigits: 4,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "GU",
          dialCode: "+1671",
          flag: "🇬🇺",
          englishName: "Guam",
          arabicName: "غوام",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "GT",
          dialCode: "+502",
          flag: "🇬🇹",
          englishName: "Guatemala",
          arabicName: "غواتيمالا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "GG",
          dialCode: "+44",
          flag: "🇬🇬",
          englishName: "Guernsey",
          arabicName: "غيرنزي",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "GN",
          dialCode: "+224",
          flag: "🇬🇳",
          englishName: "Guinea",
          arabicName: "غينيا",
          minNationalDigits: 8,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "GW",
          dialCode: "+245",
          flag: "🇬🇼",
          englishName: "Guinea-Bissau",
          arabicName: "غينيا بيساو",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "GY",
          dialCode: "+592",
          flag: "🇬🇾",
          englishName: "Guyana",
          arabicName: "غيانا",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "HT",
          dialCode: "+509",
          flag: "🇭🇹",
          englishName: "Haiti",
          arabicName: "هايتي",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "HM",
          dialCode: "+672",
          flag: "🇭🇲",
          englishName: "Heard Island and Mcdonald Islands",
          arabicName: "جزيرة هيرد وجزر ماكدونالد",
          minNationalDigits: 4,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "VA",
          dialCode: "+379",
          flag: "🇻🇦",
          englishName: "Holy See (Vatican City State)",
          arabicName: "الفاتيكان",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "HN",
          dialCode: "+504",
          flag: "🇭🇳",
          englishName: "Honduras",
          arabicName: "هندوراس",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "HK",
          dialCode: "+852",
          flag: "🇭🇰",
          englishName: "Hong Kong",
          arabicName: "هونغ كونغ",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "HU",
          dialCode: "+36",
          flag: "🇭🇺",
          englishName: "Hungary",
          arabicName: "المجر",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "IS",
          dialCode: "+354",
          flag: "🇮🇸",
          englishName: "Iceland",
          arabicName: "آيسلندا",
          minNationalDigits: 7,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "IN",
          dialCode: "+91",
          flag: "🇮🇳",
          englishName: "India",
          arabicName: "الهند",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "ID",
          dialCode: "+62",
          flag: "🇮🇩",
          englishName: "Indonesia",
          arabicName: "إندونيسيا",
          minNationalDigits: 10,
          maxNationalDigits: 13,
        ),
        RegistrationCountryMetadata(
          code: "IR",
          dialCode: "+98",
          flag: "🇮🇷",
          englishName: "Iran, Islamic Republic of Persian Gulf",
          arabicName: "إيران",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "IQ",
          dialCode: "+964",
          flag: "🇮🇶",
          englishName: "Iraq",
          arabicName: "العراق",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "IE",
          dialCode: "+353",
          flag: "🇮🇪",
          englishName: "Ireland",
          arabicName: "أيرلندا",
          minNationalDigits: 7,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "IM",
          dialCode: "+44",
          flag: "🇮🇲",
          englishName: "Isle of Man",
          arabicName: "جزيرة مان",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "IL",
          dialCode: "+972",
          flag: "🇮🇱",
          englishName: "Israel",
          arabicName: "إسرائيل",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "IT",
          dialCode: "+39",
          flag: "🇮🇹",
          englishName: "Italy",
          arabicName: "إيطاليا",
          minNationalDigits: 6,
          maxNationalDigits: 11,
        ),
        RegistrationCountryMetadata(
          code: "JM",
          dialCode: "+1876",
          flag: "🇯🇲",
          englishName: "Jamaica",
          arabicName: "جامايكا",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "JP",
          dialCode: "+81",
          flag: "🇯🇵",
          englishName: "Japan",
          arabicName: "اليابان",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "JE",
          dialCode: "+44",
          flag: "🇯🇪",
          englishName: "Jersey",
          arabicName: "جيرزي",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "JO",
          dialCode: "+962",
          flag: "🇯🇴",
          englishName: "Jordan",
          arabicName: "الأردن",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "KZ",
          dialCode: "+7",
          flag: "🇰🇿",
          englishName: "Kazakhstan",
          arabicName: "كازاخستان",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "KE",
          dialCode: "+254",
          flag: "🇰🇪",
          englishName: "Kenya",
          arabicName: "كينيا",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "KI",
          dialCode: "+686",
          flag: "🇰🇮",
          englishName: "Kiribati",
          arabicName: "كيريباتي",
          minNationalDigits: 5,
          maxNationalDigits: 5,
        ),
        RegistrationCountryMetadata(
          code: "KP",
          dialCode: "+850",
          flag: "🇰🇵",
          englishName: "Korea, Democratic People's Republic of Korea",
          arabicName: "كوريا الشمالية",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "KR",
          dialCode: "+82",
          flag: "🇰🇷",
          englishName: "Korea, Republic of South Korea",
          arabicName: "كوريا الجنوبية",
          minNationalDigits: 11,
          maxNationalDigits: 11,
        ),
        RegistrationCountryMetadata(
          code: "KW",
          dialCode: "+965",
          flag: "🇰🇼",
          englishName: "Kuwait",
          arabicName: "الكويت",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "KG",
          dialCode: "+996",
          flag: "🇰🇬",
          englishName: "Kyrgyzstan",
          arabicName: "قيرغيزستان",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "LA",
          dialCode: "+856",
          flag: "🇱🇦",
          englishName: "Laos",
          arabicName: "لاوس",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "LV",
          dialCode: "+371",
          flag: "🇱🇻",
          englishName: "Latvia",
          arabicName: "لاتفيا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "LB",
          dialCode: "+961",
          flag: "🇱🇧",
          englishName: "Lebanon",
          arabicName: "لبنان",
          minNationalDigits: 7,
          maxNationalDigits: 8,
          nationalPrefix: "0",
        ),
        RegistrationCountryMetadata(
          code: "LS",
          dialCode: "+266",
          flag: "🇱🇸",
          englishName: "Lesotho",
          arabicName: "ليسوتو",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "LR",
          dialCode: "+231",
          flag: "🇱🇷",
          englishName: "Liberia",
          arabicName: "ليبيريا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "LY",
          dialCode: "+218",
          flag: "🇱🇾",
          englishName: "Libyan Arab Jamahiriya",
          arabicName: "ليبيا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
          nationalPrefix: "0",
        ),
        RegistrationCountryMetadata(
          code: "LI",
          dialCode: "+423",
          flag: "🇱🇮",
          englishName: "Liechtenstein",
          arabicName: "ليختنشتاين",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "LT",
          dialCode: "+370",
          flag: "🇱🇹",
          englishName: "Lithuania",
          arabicName: "ليتوانيا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "LU",
          dialCode: "+352",
          flag: "🇱🇺",
          englishName: "Luxembourg",
          arabicName: "لوكسمبورغ",
          minNationalDigits: 11,
          maxNationalDigits: 11,
        ),
        RegistrationCountryMetadata(
          code: "MO",
          dialCode: "+853",
          flag: "🇲🇴",
          englishName: "Macao",
          arabicName: "ماكاو",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "MK",
          dialCode: "+389",
          flag: "🇲🇰",
          englishName: "Macedonia",
          arabicName: "مقدونيا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "MG",
          dialCode: "+261",
          flag: "🇲🇬",
          englishName: "Madagascar",
          arabicName: "مدغشقر",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "MW",
          dialCode: "+265",
          flag: "🇲🇼",
          englishName: "Malawi",
          arabicName: "مالاوي",
          minNationalDigits: 7,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "MY",
          dialCode: "+60",
          flag: "🇲🇾",
          englishName: "Malaysia",
          arabicName: "ماليزيا",
          minNationalDigits: 11,
          maxNationalDigits: 11,
        ),
        RegistrationCountryMetadata(
          code: "MV",
          dialCode: "+960",
          flag: "🇲🇻",
          englishName: "Maldives",
          arabicName: "جزر المالديف",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "ML",
          dialCode: "+223",
          flag: "🇲🇱",
          englishName: "Mali",
          arabicName: "مالي",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "MT",
          dialCode: "+356",
          flag: "🇲🇹",
          englishName: "Malta",
          arabicName: "مالطا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "MH",
          dialCode: "+692",
          flag: "🇲🇭",
          englishName: "Marshall Islands",
          arabicName: "جزر مارشال",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "MQ",
          dialCode: "+596",
          flag: "🇲🇶",
          englishName: "Martinique",
          arabicName: "مارتينيك",
          minNationalDigits: 4,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "MR",
          dialCode: "+222",
          flag: "🇲🇷",
          englishName: "Mauritania",
          arabicName: "موريتانيا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "MU",
          dialCode: "+230",
          flag: "🇲🇺",
          englishName: "Mauritius",
          arabicName: "موريشيوس",
          minNationalDigits: 7,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "YT",
          dialCode: "+262",
          flag: "🇾🇹",
          englishName: "Mayotte",
          arabicName: "مايوت",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "MX",
          dialCode: "+52",
          flag: "🇲🇽",
          englishName: "Mexico",
          arabicName: "المكسيك",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "FM",
          dialCode: "+691",
          flag: "🇫🇲",
          englishName: "Micronesia, Federated States of Micronesia",
          arabicName: "ولايات ميكرونيسيا المتحدة",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "MD",
          dialCode: "+373",
          flag: "🇲🇩",
          englishName: "Moldova",
          arabicName: "مولدوفا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "MC",
          dialCode: "+377",
          flag: "🇲🇨",
          englishName: "Monaco",
          arabicName: "موناكو",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "MN",
          dialCode: "+976",
          flag: "🇲🇳",
          englishName: "Mongolia",
          arabicName: "منغوليا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "ME",
          dialCode: "+382",
          flag: "🇲🇪",
          englishName: "Montenegro",
          arabicName: "الجبل الأسود",
          minNationalDigits: 12,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "MS",
          dialCode: "+1664",
          flag: "🇲🇸",
          englishName: "Montserrat",
          arabicName: "مونتسرات",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "MA",
          dialCode: "+212",
          flag: "🇲🇦",
          englishName: "Morocco",
          arabicName: "المغرب",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "MZ",
          dialCode: "+258",
          flag: "🇲🇿",
          englishName: "Mozambique",
          arabicName: "موزمبيق",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "MM",
          dialCode: "+95",
          flag: "🇲🇲",
          englishName: "Myanmar",
          arabicName: "ميانمار",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "NA",
          dialCode: "+264",
          flag: "🇳🇦",
          englishName: "Namibia",
          arabicName: "ناميبيا",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "NR",
          dialCode: "+674",
          flag: "🇳🇷",
          englishName: "Nauru",
          arabicName: "ناورو",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "NP",
          dialCode: "+977",
          flag: "🇳🇵",
          englishName: "Nepal",
          arabicName: "نيبال",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "NL",
          dialCode: "+31",
          flag: "🇳🇱",
          englishName: "Netherlands",
          arabicName: "هولندا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
          nationalPrefix: "0",
        ),
        RegistrationCountryMetadata(
          code: "NC",
          dialCode: "+687",
          flag: "🇳🇨",
          englishName: "New Caledonia",
          arabicName: "كاليدونيا الجديدة",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "NZ",
          dialCode: "+64",
          flag: "🇳🇿",
          englishName: "New Zealand",
          arabicName: "نيوزيلندا",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "NI",
          dialCode: "+505",
          flag: "🇳🇮",
          englishName: "Nicaragua",
          arabicName: "نيكاراغوا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "NE",
          dialCode: "+227",
          flag: "🇳🇪",
          englishName: "Niger",
          arabicName: "النيجر",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "NG",
          dialCode: "+234",
          flag: "🇳🇬",
          englishName: "Nigeria",
          arabicName: "نيجيريا",
          minNationalDigits: 10,
          maxNationalDigits: 11,
        ),
        RegistrationCountryMetadata(
          code: "NU",
          dialCode: "+683",
          flag: "🇳🇺",
          englishName: "Niue",
          arabicName: "نييوي",
          minNationalDigits: 4,
          maxNationalDigits: 4,
        ),
        RegistrationCountryMetadata(
          code: "NF",
          dialCode: "+672",
          flag: "🇳🇫",
          englishName: "Norfolk Island",
          arabicName: "جزيرة نورفولك",
          minNationalDigits: 4,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "MP",
          dialCode: "+1670",
          flag: "🇲🇵",
          englishName: "Northern Mariana Islands",
          arabicName: "جزر ماريانا الشمالية",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "NO",
          dialCode: "+47",
          flag: "🇳🇴",
          englishName: "Norway",
          arabicName: "النرويج",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "OM",
          dialCode: "+968",
          flag: "🇴🇲",
          englishName: "Oman",
          arabicName: "عمان",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "PK",
          dialCode: "+92",
          flag: "🇵🇰",
          englishName: "Pakistan",
          arabicName: "باكستان",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "PW",
          dialCode: "+680",
          flag: "🇵🇼",
          englishName: "Palau",
          arabicName: "بالاو",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "PS",
          dialCode: "+970",
          flag: "🇵🇸",
          englishName: "Palestinian Territory, Occupied",
          arabicName: "فلسطين",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "PA",
          dialCode: "+507",
          flag: "🇵🇦",
          englishName: "Panama",
          arabicName: "بنما",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "PG",
          dialCode: "+675",
          flag: "🇵🇬",
          englishName: "Papua New Guinea",
          arabicName: "بابوا غينيا الجديدة",
          minNationalDigits: 11,
          maxNationalDigits: 11,
        ),
        RegistrationCountryMetadata(
          code: "PY",
          dialCode: "+595",
          flag: "🇵🇾",
          englishName: "Paraguay",
          arabicName: "باراغواي",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "PE",
          dialCode: "+51",
          flag: "🇵🇪",
          englishName: "Peru",
          arabicName: "بيرو",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "PH",
          dialCode: "+63",
          flag: "🇵🇭",
          englishName: "Philippines",
          arabicName: "الفلبين",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "PN",
          dialCode: "+64",
          flag: "🇵🇳",
          englishName: "Pitcairn",
          arabicName: "جزر بيتكيرن",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "PL",
          dialCode: "+48",
          flag: "🇵🇱",
          englishName: "Poland",
          arabicName: "بولندا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "PT",
          dialCode: "+351",
          flag: "🇵🇹",
          englishName: "Portugal",
          arabicName: "البرتغال",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "PR",
          dialCode: "+1939",
          flag: "🇵🇷",
          englishName: "Puerto Rico",
          arabicName: "بورتوريكو",
          minNationalDigits: 4,
          maxNationalDigits: 11,
        ),
        RegistrationCountryMetadata(
          code: "QA",
          dialCode: "+974",
          flag: "🇶🇦",
          englishName: "Qatar",
          arabicName: "قطر",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "RO",
          dialCode: "+40",
          flag: "🇷🇴",
          englishName: "Romania",
          arabicName: "رومانيا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "RU",
          dialCode: "+7",
          flag: "🇷🇺",
          englishName: "Russia",
          arabicName: "روسيا",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "RW",
          dialCode: "+250",
          flag: "🇷🇼",
          englishName: "Rwanda",
          arabicName: "رواندا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "RE",
          dialCode: "+262",
          flag: "🇷🇪",
          englishName: "Reunion",
          arabicName: "لا ريونيون",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "BL",
          dialCode: "+590",
          flag: "🇧🇱",
          englishName: "Saint Barthelemy",
          arabicName: "سان بارتيلمي",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "SH",
          dialCode: "+290",
          flag: "🇸🇭",
          englishName: "Saint Helena, Ascension and Tristan Da Cunha",
          arabicName: "سانت هيلانة وأسينشين وتريستان دا كونا",
          minNationalDigits: 4,
          maxNationalDigits: 4,
        ),
        RegistrationCountryMetadata(
          code: "KN",
          dialCode: "+1869",
          flag: "🇰🇳",
          englishName: "Saint Kitts and Nevis",
          arabicName: "سانت كيتس ونيفيس",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "LC",
          dialCode: "+1758",
          flag: "🇱🇨",
          englishName: "Saint Lucia",
          arabicName: "سانت لوسيا",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "MF",
          dialCode: "+590",
          flag: "🇲🇫",
          englishName: "Saint Martin",
          arabicName: "تجمع سان مارتين",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "PM",
          dialCode: "+508",
          flag: "🇵🇲",
          englishName: "Saint Pierre and Miquelon",
          arabicName: "سان بيير وميكلون",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "VC",
          dialCode: "+1784",
          flag: "🇻🇨",
          englishName: "Saint Vincent and the Grenadines",
          arabicName: "سانت فينسنت والغرينادين",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "WS",
          dialCode: "+685",
          flag: "🇼🇸",
          englishName: "Samoa",
          arabicName: "ساموا",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "SM",
          dialCode: "+378",
          flag: "🇸🇲",
          englishName: "San Marino",
          arabicName: "سان مارينو",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "ST",
          dialCode: "+239",
          flag: "🇸🇹",
          englishName: "Sao Tome and Principe",
          arabicName: "ساو تومي وبرينسيب",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "SA",
          dialCode: "+966",
          flag: "🇸🇦",
          englishName: "Saudi Arabia",
          arabicName: "السعودية",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "SN",
          dialCode: "+221",
          flag: "🇸🇳",
          englishName: "Senegal",
          arabicName: "السنغال",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "RS",
          dialCode: "+381",
          flag: "🇷🇸",
          englishName: "Serbia",
          arabicName: "صربيا",
          minNationalDigits: 12,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "SC",
          dialCode: "+248",
          flag: "🇸🇨",
          englishName: "Seychelles",
          arabicName: "سيشل",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "SL",
          dialCode: "+232",
          flag: "🇸🇱",
          englishName: "Sierra Leone",
          arabicName: "سيراليون",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "SG",
          dialCode: "+65",
          flag: "🇸🇬",
          englishName: "Singapore",
          arabicName: "سنغافورة",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "SK",
          dialCode: "+421",
          flag: "🇸🇰",
          englishName: "Slovakia",
          arabicName: "سلوفاكيا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "SI",
          dialCode: "+386",
          flag: "🇸🇮",
          englishName: "Slovenia",
          arabicName: "سلوفينيا",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "SB",
          dialCode: "+677",
          flag: "🇸🇧",
          englishName: "Solomon Islands",
          arabicName: "جزر سليمان",
          minNationalDigits: 5,
          maxNationalDigits: 5,
        ),
        RegistrationCountryMetadata(
          code: "SO",
          dialCode: "+252",
          flag: "🇸🇴",
          englishName: "Somalia",
          arabicName: "الصومال",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "ZA",
          dialCode: "+27",
          flag: "🇿🇦",
          englishName: "South Africa",
          arabicName: "جنوب أفريقيا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "SS",
          dialCode: "+211",
          flag: "🇸🇸",
          englishName: "South Sudan",
          arabicName: "جنوب السودان",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "GS",
          dialCode: "+500",
          flag: "🇬🇸",
          englishName: "South Georgia and the South Sandwich Islands",
          arabicName: "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
          minNationalDigits: 4,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "ES",
          dialCode: "+34",
          flag: "🇪🇸",
          englishName: "Spain",
          arabicName: "إسبانيا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "LK",
          dialCode: "+94",
          flag: "🇱🇰",
          englishName: "Sri Lanka",
          arabicName: "سريلانكا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "SD",
          dialCode: "+249",
          flag: "🇸🇩",
          englishName: "Sudan",
          arabicName: "السودان",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "SR",
          dialCode: "+597",
          flag: "🇸🇷",
          englishName: "Suriname",
          arabicName: "سورينام",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "SJ",
          dialCode: "+47",
          flag: "🇸🇯",
          englishName: "Svalbard and Jan Mayen",
          arabicName: "سفالبارد ويان ماين",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "SZ",
          dialCode: "+268",
          flag: "🇸🇿",
          englishName: "Eswatini",
          arabicName: "إسواتيني",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "SE",
          dialCode: "+46",
          flag: "🇸🇪",
          englishName: "Sweden",
          arabicName: "السويد",
          minNationalDigits: 7,
          maxNationalDigits: 13,
        ),
        RegistrationCountryMetadata(
          code: "CH",
          dialCode: "+41",
          flag: "🇨🇭",
          englishName: "Switzerland",
          arabicName: "سويسرا",
          minNationalDigits: 9,
          maxNationalDigits: 12,
        ),
        RegistrationCountryMetadata(
          code: "SY",
          dialCode: "+963",
          flag: "🇸🇾",
          englishName: "Syrian Arab Republic",
          arabicName: "سوريا",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "TW",
          dialCode: "+886",
          flag: "🇹🇼",
          englishName: "Taiwan",
          arabicName: "تايوان",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "TJ",
          dialCode: "+992",
          flag: "🇹🇯",
          englishName: "Tajikistan",
          arabicName: "طاجيكستان",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "TZ",
          dialCode: "+255",
          flag: "🇹🇿",
          englishName: "Tanzania, United Republic of Tanzania",
          arabicName: "تنزانيا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "TH",
          dialCode: "+66",
          flag: "🇹🇭",
          englishName: "Thailand",
          arabicName: "تايلاند",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "TL",
          dialCode: "+670",
          flag: "🇹🇱",
          englishName: "Timor-Leste",
          arabicName: "تيمور الشرقية",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "TG",
          dialCode: "+228",
          flag: "🇹🇬",
          englishName: "Togo",
          arabicName: "توغو",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "TK",
          dialCode: "+690",
          flag: "🇹🇰",
          englishName: "Tokelau",
          arabicName: "توكيلاو",
          minNationalDigits: 4,
          maxNationalDigits: 4,
        ),
        RegistrationCountryMetadata(
          code: "TO",
          dialCode: "+676",
          flag: "🇹🇴",
          englishName: "Tonga",
          arabicName: "تونغا",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "TT",
          dialCode: "+1868",
          flag: "🇹🇹",
          englishName: "Trinidad and Tobago",
          arabicName: "ترينيداد وتوباغو",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "TN",
          dialCode: "+216",
          flag: "🇹🇳",
          englishName: "Tunisia",
          arabicName: "تونس",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "TR",
          dialCode: "+90",
          flag: "🇹🇷",
          englishName: "Turkey",
          arabicName: "تركيا",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "TM",
          dialCode: "+993",
          flag: "🇹🇲",
          englishName: "Turkmenistan",
          arabicName: "تركمانستان",
          minNationalDigits: 8,
          maxNationalDigits: 8,
        ),
        RegistrationCountryMetadata(
          code: "TC",
          dialCode: "+1649",
          flag: "🇹🇨",
          englishName: "Turks and Caicos Islands",
          arabicName: "جزر توركس وكايكوس",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "TV",
          dialCode: "+688",
          flag: "🇹🇻",
          englishName: "Tuvalu",
          arabicName: "توفالو",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "UG",
          dialCode: "+256",
          flag: "🇺🇬",
          englishName: "Uganda",
          arabicName: "أوغندا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "UA",
          dialCode: "+380",
          flag: "🇺🇦",
          englishName: "Ukraine",
          arabicName: "أوكرانيا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "AE",
          dialCode: "+971",
          flag: "🇦🇪",
          englishName: "United Arab Emirates",
          arabicName: "الإمارات العربية المتحدة",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "GB",
          dialCode: "+44",
          flag: "🇬🇧",
          englishName: "United Kingdom",
          arabicName: "المملكة المتحدة",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "US",
          dialCode: "+1",
          flag: "🇺🇸",
          englishName: "United States",
          arabicName: "الولايات المتحدة",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "UY",
          dialCode: "+598",
          flag: "🇺🇾",
          englishName: "Uruguay",
          arabicName: "الأوروغواي",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "UZ",
          dialCode: "+998",
          flag: "🇺🇿",
          englishName: "Uzbekistan",
          arabicName: "أوزبكستان",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "VU",
          dialCode: "+678",
          flag: "🇻🇺",
          englishName: "Vanuatu",
          arabicName: "فانواتو",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "VE",
          dialCode: "+58",
          flag: "🇻🇪",
          englishName: "Venezuela, Bolivarian Republic of Venezuela",
          arabicName: "فنزويلا",
          minNationalDigits: 10,
          maxNationalDigits: 10,
        ),
        RegistrationCountryMetadata(
          code: "VN",
          dialCode: "+84",
          flag: "🇻🇳",
          englishName: "Vietnam",
          arabicName: "فيتنام",
          minNationalDigits: 11,
          maxNationalDigits: 11,
        ),
        RegistrationCountryMetadata(
          code: "VG",
          dialCode: "+1284",
          flag: "🇻🇬",
          englishName: "Virgin Islands, British",
          arabicName: "جزر العذراء البريطانية",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "VI",
          dialCode: "+1340",
          flag: "🇻🇮",
          englishName: "Virgin Islands, U.S.",
          arabicName: "جزر العذراء الأمريكية",
          minNationalDigits: 7,
          maxNationalDigits: 7,
        ),
        RegistrationCountryMetadata(
          code: "WF",
          dialCode: "+681",
          flag: "🇼🇫",
          englishName: "Wallis and Futuna",
          arabicName: "والس وفوتونا",
          minNationalDigits: 6,
          maxNationalDigits: 6,
        ),
        RegistrationCountryMetadata(
          code: "YE",
          dialCode: "+967",
          flag: "🇾🇪",
          englishName: "Yemen",
          arabicName: "اليمن",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "ZM",
          dialCode: "+260",
          flag: "🇿🇲",
          englishName: "Zambia",
          arabicName: "زامبيا",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
        RegistrationCountryMetadata(
          code: "ZW",
          dialCode: "+263",
          flag: "🇿🇼",
          englishName: "Zimbabwe",
          arabicName: "زيمبابوي",
          minNationalDigits: 9,
          maxNationalDigits: 9,
        ),
      ];

  static RegistrationCountryMetadata get defaultCountry =>
      byCode(defaultCountryCode)!;

  static RegistrationCountryMetadata? byCode(String code) {
    for (final country in all) {
      if (country.code == code) return country;
    }
    return null;
  }
}
