/// Shared foundation for Flutter widget previews (`flutter widget-preview
/// start`).
///
/// A preview is a top-level function returning a widget, annotated with
/// [JeebPreview]. The annotation expands into the review matrix this app
/// actually needs — see [JeebPreview.previews] — so no author has to remember
/// to check Arabic or large text by hand.
///
/// Previews MUST live under `lib/`: the preview scaffold generated by
/// `flutter_tools` imports them as `package:` URIs, so a file outside `lib/`
/// is invisible to the tool. They cost nothing in a release build — an
/// unreferenced top-level function is tree-shaken by the AOT compiler, and
/// nothing in the app ever calls one.
///
/// This is the preview-side sibling of the on-device Screen Catalog
/// (`lib/devtool/catalog/`): the catalog is the designer's in-app browser of
/// whole screens; previews are the engineer's desktop loop for single widgets.
/// Both share [CatalogNetworkGuard] so neither can mutate the live gateway.
library;

import 'package:flutter/material.dart';
import 'package:flutter/widget_previews.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import '../../core/theme/app_theme.dart';
import '../../l10n/app_localizations.dart';
import '../../devtool/catalog/catalog_network_guard.dart';

/// Both real app themes, so previews render the true tier colors and semantic
/// color roles rather than a stock Material palette.
PreviewThemeData jeebPreviewTheme() => PreviewThemeData(
      materialLight: AppTheme.light(),
      materialDark: AppTheme.dark(),
    );

/// English (LTR) localizations, using the app's real delegate.
PreviewLocalizationsData jeebPreviewEnglish() => const PreviewLocalizationsData(
      locale: Locale('en'),
      supportedLocales: AppLocalizations.supportedLocales,
      localizationsDelegates: _delegates,
    );

/// Arabic (RTL) localizations, using the app's real delegate.
///
/// Arabic is not an afterthought here: the app ships 1534 keys in both EN and
/// AR, and RTL mirroring is where header/row layouts break first. Every
/// [JeebPreview] renders it.
PreviewLocalizationsData jeebPreviewArabic() => const PreviewLocalizationsData(
      locale: Locale('ar'),
      supportedLocales: AppLocalizations.supportedLocales,
      localizationsDelegates: _delegates,
    );

const List<LocalizationsDelegate<Object?>> _delegates =
    <LocalizationsDelegate<Object?>>[
  AppLocalizations.delegate,
  GlobalMaterialLocalizations.delegate,
  GlobalWidgetsLocalizations.delegate,
  GlobalCupertinoLocalizations.delegate,
];

/// Wraps every previewed widget in the app's real surface plus the fail-closed
/// network guard.
///
/// The guard is the same one the Screen Catalog installs: any repository seam a
/// fixture missed can still read (GET/HEAD/OPTIONS), but every mutating verb is
/// rejected locally before Dio reaches its HTTP adapter. It no-ops safely when
/// the DI graph was never built, which is the normal case in a preview.
Widget jeebPreviewHost(Widget child) => CatalogNetworkGuard(
      builder: (_) => Scaffold(body: SafeArea(child: child)),
    );

/// The standard Jeeb preview matrix: one annotation, three renderings.
///
/// * **EN light** — the default reading.
/// * **AR RTL dark** — catches unmirrored padding, hardcoded `EdgeInsets.only`
///   left/right, and unlocalized strings, plus dark-mode contrast, in one pass.
/// * **EN 200% text** — the accessibility ceiling the golden tests already
///   assert for a few screens (`test/**/goldens/*_200_percent_text.png`);
///   this puts every previewed widget under the same lens.
///
/// Pass [size] to give the canvas a sensible box for the widget under review —
/// a header wants a short wide box, a card wants something near phone width.
///
/// ## Why the matrix is OFF by default
///
/// Rendering all three variants for every widget put ~750 cards in one flat
/// canvas, which is both slow to first paint and hard to navigate. The AR and
/// 200% renderings are still asserted on every CI run — see
/// `test/previews/preview_test_harness.dart`, which pumps each preview in BOTH
/// locales — so the canvas does not have to carry them to keep them honest.
///
/// Pass `matrix: true` on the previews where seeing them side by side is the
/// point: anything with a Row of text and actions, any RTL-sensitive layout,
/// anything whose copy length varies by locale.
final class JeebPreview extends MultiPreview {
  const JeebPreview({
    this.name,
    this.size,
    this.group = 'Other',
    this.matrix = false,
  });

  /// Label for this preview in the canvas. When [matrix] is on, each rendering
  /// is suffixed with its own variant name.
  final String? name;

  /// Canvas size. Defaults to a phone-width box when omitted.
  final Size? size;

  /// Collapsible section this preview lands in — use the feature area, so the
  /// canvas groups by `chat`, `core`, `live_tracking` … instead of presenting
  /// one undifferentiated wall. This is also the reliable way to navigate:
  /// the canvas's own search box renders the wrong previews (it filters labels
  /// but paints by unfiltered index) in Flutter 3.44.2.
  final String group;

  /// Render the full EN-light / AR-RTL-dark / EN-200%-text matrix instead of
  /// the default single EN-light card.
  final bool matrix;

  static const Size _defaultSize = Size(390, 200);

  @override
  List<Preview> get previews {
    final Size box = size ?? _defaultSize;
    if (!matrix) {
      return <Preview>[
        Preview(
          name: name,
          group: group,
          size: box,
          brightness: Brightness.light,
          theme: jeebPreviewTheme,
          localizations: jeebPreviewEnglish,
          wrapper: jeebPreviewHost,
        ),
      ];
    }
    final String prefix = name == null ? '' : '$name · ';
    return <Preview>[
      Preview(
        name: '${prefix}EN light',
        group: group,
        size: box,
        brightness: Brightness.light,
        theme: jeebPreviewTheme,
        localizations: jeebPreviewEnglish,
        wrapper: jeebPreviewHost,
      ),
      Preview(
        name: '${prefix}AR RTL dark',
        group: group,
        size: box,
        brightness: Brightness.dark,
        theme: jeebPreviewTheme,
        localizations: jeebPreviewArabic,
        wrapper: jeebPreviewHost,
      ),
      Preview(
        name: '${prefix}EN 200% text',
        group: group,
        size: box,
        textScaleFactor: 2.0,
        brightness: Brightness.light,
        theme: jeebPreviewTheme,
        localizations: jeebPreviewEnglish,
        wrapper: jeebPreviewHost,
      ),
    ];
  }
}
