/// Widget previews for [CustomerProfileHeader] — run with
/// `flutter widget-preview start`.
///
/// The header is a pure [StatelessWidget] over six plain fields, so every state
/// below is just a constructor call: no cubit, no repository, nothing to seed.
/// It is network-free by construction, not merely by [jeebPreviewHost]'s guard.
///
/// **Why there is no "avatar photo" state.** `avatarUrl` is the one field that
/// would reach the network (`OmdsProfileAvatar` → `OmdsCachedImage`), and a CDN
/// URL resolves in neither the canvas nor a test — both fall back to the same
/// initials placeholder the `null` states already show. A preview that renders
/// identically to its neighbours is the exact failure `expectedText` exists to
/// catch, so every state here passes `avatarUrl: null` and the photo path is
/// left to the screen goldens.
///
/// Fixture values are the ones already asserted in
/// `test/customer_profile_screen_test.dart` (`_ratedCustomer`,
/// `_unratedCustomer`, `_jeeberCustomer`) so the previews and the screen test
/// describe the same customers.
///
/// **Measured geometry** (390 dp wide, bundled Inter, from the render tree —
/// not eyeballed). The identity column gets 222 dp: 390 − 24 − 24 of
/// directional padding − 80 dp avatar − 12 dp gap − 28 dp for the verified
/// badge and its gap. Header heights:
///
/// | state              | 1x     | 200% text |
/// |--------------------|--------|-----------|
/// | cold start         | 152 dp | 172 dp    |
/// | rated / unrated    | 152 dp | 320 dp    |
/// | Arabic name        | 184 dp | 384 dp    |
/// | synthetic identity | 204 dp | 424 dp    |
/// | long name          | 236 dp | 592 dp    |
///
/// Each canvas box below is sized to hold its own 200% rendering, so an
/// overflow stripe in the canvas means a real regression — except in the last
/// state, where the overflow IS the subject.
library;

import 'package:flutter/material.dart';

import '../harness/jeeb_preview.dart';
import '../../features/customer_profile/presentation/widgets/customer_profile_header.dart';

/// Phone width; holds the 56 dp top inset + the 80 dp avatar + a
/// single-line-per-row identity column, with room for the 320 dp the same
/// content needs at 200% text.
const Size _headerBox = Size(390, 340);

/// For the states whose identity column wraps to a second line even at 1x
/// (long email, Arabic name) — 424 dp at 200% is the tallest of them.
const Size _wrappingBox = Size(390, 440);

/// A whole phone viewport, because that is the point of the state it frames:
/// at 200% text the header alone fills the screen.
const Size _phoneScreenBox = Size(390, 600);

/// One specimen. Mirrors the argument list `CustomerProfileScreen` passes at
/// `lib/features/customer_profile/presentation/customer_profile_screen.dart:142`
/// — same six fields, same order, so a preview cannot drift from the call site.
Widget _hosted({
  String? name,
  String? email,
  bool isVerified = false,
  double? rating,
  int ratingCount = 0,
}) {
  return CustomerProfileHeader(
    name: name,
    email: email,
    // Always null — see the library doc above.
    avatarUrl: null,
    isVerified: isVerified,
    rating: rating,
    ratingCount: ratingCount,
  );
}

/// The happy path: a rated, verified customer with an email on file
/// (`_ratedCustomer` from the screen test).
///
/// All four elements present at once — initials avatar, name + SealCheck badge,
/// "★ 4.8 · 42 Reviews", email — the only state where the identity column runs
/// to its full three rows. Two things to check in **AR RTL dark**: the star
/// leads the rating text (a plain [Row], so it relies entirely on ambient
/// [Directionality]), and the Latin email still reads LTR inside the mirrored
/// column — that is what `AutoDirectionText` is there for.
///
/// The dark rendering is also where the name's colour shows itself: it is
/// painted with `colorScheme.secondaryContainer`, a *container* role used as
/// ink. On white that is brand navy (17:1), but the dark scheme is generated by
/// `ColorScheme.fromSeed`, where the same role is #44455A — 1.98:1 against the
/// #131318 surface, under the 3:1 WCAG floor for large text. The rating and
/// email lines beside it use `onSurfaceVariant` and stay at 10.9:1.
@JeebPreview(name: 'Rated + verified', size: _headerBox)
Widget customerProfileHeaderRated() => _hosted(
      name: 'Sami Fawaz',
      email: 'kamalhaaj@gmail.com',
      isVerified: true,
      rating: 4.8,
      ratingCount: 42,
    );

/// The seeded customer: verified, but never rated and with no email
/// (`_unratedCustomer` from the screen test — `user-client-001` carries
/// neither).
///
/// Two branches fire at once. [CustomerProfileRating] swaps to the outlined
/// star + "No reviews yet" rather than disappearing, because the
/// `customer_profile_rating` identifier has to survive for the JM-035 Maestro
/// presence assertion. `_Identity` then drops the email row entirely
/// (`if (email != null)`), so the column loses a line and the 80 dp avatar
/// becomes the tallest thing in the row. This is what most real accounts look
/// like on first open.
@JeebPreview(name: 'Unrated, no email', size: _headerBox)
Widget customerProfileHeaderUnrated() => _hosted(
      name: 'Nadia Client',
      isVerified: true,
    );

/// Cold start: `GET /user-management/users/me` has not resolved yet.
///
/// Not hypothetical — `lib/features/shell/shell_screen.dart:341` mounts the
/// profile tab as `CustomerProfileScreen(data: CustomerProfileViewData())`,
/// every field null, so this is the first frame of the tab for everyone. The
/// avatar falls back to "?", the badge is gone, the rating chip shows its empty
/// state, and the name line collapses to an empty [Text] — which is the part
/// worth looking at. There is no skeleton and no placeholder, just a gap where
/// the name will appear, and the `customer_profile_name` Semantics node is
/// left with `label: ''`, so a screen reader lands on a node that announces
/// nothing.
@JeebPreview(name: 'Cold start (nothing loaded)', size: _headerBox)
Widget customerProfileHeaderColdStart() => _hosted();

/// A phone-only account, exactly as `getMe` returns it.
///
/// Jeeb mints synthetic identities for OTP-only signups — a `jeeb-<hash>` name
/// and a `phone-only+<hash>@jeeb.internal` email (see
/// `lib/core/formatting/friendly_reference.dart`, and the live fixture in
/// `test/features/request_summary/signin_persists_recipient_phone_e2e_test.dart`).
/// `DioCustomerProfileRepository._parse` passes both straight through without
/// calling `displayNameOrNull`, unlike `ClientHomeGreeting`, the offer cards
/// and the chat pinned summary, which all suppress them. So this preview shows
/// the sprint-009 §T5 leak the greeting surfaces were fixed for, still live on
/// the one screen a customer opens to check who they are: a machine handle
/// where their name goes, an internal routing address where their email goes.
@JeebPreview(name: 'Phone-only synthetic identity', size: _wrappingBox)
Widget customerProfileHeaderSyntheticIdentity() => _hosted(
      name: 'jeeb-e1a35ea8a520',
      email: 'phone-only+cb39e21caa82@jeeb.internal',
      isVerified: true,
      rating: 4.9,
      ratingCount: 312,
    );

/// An Arabic name beside a Latin email — the majority case for this app, and
/// the mixed-direction state `AutoDirectionText` exists to serve.
///
/// The two lines resolve their direction independently, from their own first
/// strong character, so in the **EN light** rendering the Arabic name lays out
/// RTL inside a left-aligned column while the email stays LTR (and the mirror
/// image of that in **AR RTL**). Whichever locale you are in, one of these two
/// lines runs against the ambient direction, and `CrossAxisAlignment.start`
/// aligns the *boxes*, not the glyphs — so this is the state where a
/// half-mirrored column would show up.
@JeebPreview(name: 'Arabic name, Latin email', size: _wrappingBox)
Widget customerProfileHeaderArabicName() => _hosted(
      name: 'كمال حاج الطرابلسي',
      email: 'kamalhaaj@gmail.com',
      isVerified: true,
      rating: 4.9,
      ratingCount: 312,
    );

/// The layout ceiling: longest plausible full name and a long email.
///
/// `_NameText` wraps its `AutoDirectionText` in a `Flexible` but passes no
/// `maxLines`/`overflow`, so unlike `ClientHomeGreeting` — which clamps its
/// name to `maxLines: 1, TextOverflow.ellipsis` — a long name here does not
/// ellipsize. It wraps and grows the header: measured, this name takes 3 lines
/// of the 222 dp column and makes the header 236 dp tall at 1x and **592 dp at
/// 200%**, which is why this box is a whole phone viewport. On the real screen
/// the header is the first child of the profile `ListView`, so those 592 dp
/// push every account row below the fold.
///
/// The verified badge is the other thing to look at. `_NameRow` centres it
/// (`CrossAxisAlignment.center`) against the *whole* wrapped block, so on a
/// 3-line name it floats beside the middle line — measured at y 94–114 against
/// a name block spanning y 56–152 — reading as an orphaned glyph rather than as
/// a mark on the name.
@JeebPreview(name: 'Long name + long email', size: _phoneScreenBox)
Widget customerProfileHeaderLongName() => _hosted(
      name: 'Abdulrahman Al-Muhandis Al-Trabulsi',
      email: 'abdulrahman.almuhandis@student-mail.university.edu.lb',
      isVerified: true,
      rating: 4.9,
      ratingCount: 312,
    );
